name: Bug Report
description: Create a report to help us improve
title: "[BUG REPORT]"
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please complete the title of the issue.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: You can attach screenshots. What did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true
  - type: input
    id: palette-version
    attributes:
      label: Palette version
      description: What version of Palette are you running?
      value: "1.0.0"
    validations:
      required: true
  - type: dropdown
    id: macos-version
    attributes:
      label: macOS version
      description: What version of macOS are you using?
      options:
        - 15.X (Sequoia)
        - 14.X (Sonoma)
      default: 0
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can now submit the issue.
        By reporting bugs, you contribute to the improvement of Palette.
